FROM n8nio/n8n:latest

ENV NODE_ENV=production
ENV N8N_PORT=5678
ENV N8N_HOST=0.0.0.0
ENV GENERIC_TIMEZONE=Asia/Kolkata
ENV N8N_DEFAULT_BINARY_DATA_MODE=filesystem
ENV N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true

EXPOSE 5678